#!/usr/bin/env Rscript
#
# This script merges label features generated by external scripts (e.g., random
# effect encoding, PMI, ...).
#

library(data.table)
library(feather)

IN <- list(
  train  = "../data/interim/3_end63_train.feather"
  , test = "../data/interim/3_end63_test.feather")

IN_MERGE <- c(
  "../data/merge/end63_dpid_ranef.rds"
  , "../data/merge/end63_dpid_day7_ranef.rds"
  , "../data/merge/end63_dpid_day10_ranef.rds")


main <- function() {
  # Merge random effect encoding.
  train <- data.table(read_feather(IN$train))
  test <- data.table(read_feather(IN$test))

  for (f in IN_MERGE) {
    enc <- readRDS(f)

    cols <- colnames(enc)[!endsWith(colnames(enc), "ref")]
    enc[, (cols) := lapply(.SD, as.integer), .SDcols = cols]

    setkeyv(train, cols)
    setkeyv(test, cols)
    setkeyv(enc, cols)

    train <- merge(train, enc, all.x = TRUE)
    test <- merge(test, enc, all.x = TRUE)
  }

  setkey(train, lineID)
  write_feather(train, "../data/end63_train.feather")

  setkey(test, lineID)
  write_feather(test, "../data/end63_test.feather")
}


main()
